# Generated by Django 2.2.20 on 2021-05-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('song1_id', models.CharField(blank=True, max_length=200)),
                ('song2_id', models.CharField(blank=True, max_length=200)),
                ('song3_id', models.CharField(blank=True, max_length=200)),
                ('song4_id', models.CharField(blank=True, max_length=200)),
                ('song5_id', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='song_listen_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('listen_count', models.IntegerField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='song_lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('lyrics', models.IntegerField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='utility_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(blank=True, max_length=1)),
            ],
        ),
    ]
