# Generated by Django 2.2.20 on 2021-05-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='karaokeGenerate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('albumArtUrl', models.CharField(blank=True, max_length=500)),
                ('audioUrl', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('song_id1', models.CharField(blank=True, max_length=200)),
                ('song_id2', models.CharField(blank=True, max_length=200)),
                ('song_id3', models.CharField(blank=True, max_length=200)),
                ('song_id4', models.CharField(blank=True, max_length=200)),
                ('song_id5', models.CharField(blank=True, max_length=200)),
                ('song_id6', models.CharField(blank=True, max_length=200)),
                ('song_id7', models.CharField(blank=True, max_length=200)),
                ('song_id8', models.CharField(blank=True, max_length=200)),
                ('song_id9', models.CharField(blank=True, max_length=200)),
                ('song_id10', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='song_listen_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('listen_count', models.IntegerField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='song_lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('lyrics', models.IntegerField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='utility_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(blank=True, max_length=1)),
            ],
        ),
    ]
