# Generated by Django 3.0.5 on 2021-05-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='karaokeGenerate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=200)),
                ('albumArtUrl', models.CharField(blank=True, max_length=500)),
                ('audioUrl', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='song1_id',
            new_name='song_id2',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='song2_id',
            new_name='song_id3',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='song3_id',
            new_name='song_id4',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='song4_id',
            new_name='song_id5',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='song5_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='song_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='song_id1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
