# Generated by Django 2.2.20 on 2021-05-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('season', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=10)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=200)),
                ('yearReleased', models.IntegerField(blank=True, max_length=4)),
                ('frequency', models.IntegerField(default=0)),
                ('albumArt', models.CharField(blank=True, max_length=200)),
                ('lyrics', models.CharField(blank=True, max_length=200)),
                ('file', models.CharField(blank=True, max_length=200)),
                ('fingerprint', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
