# Generated by Django 2.2.20 on 2021-05-03 22:54

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('season', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=10)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField(blank=True)),
                ('yearReleased', models.IntegerField(blank=True, max_length=4)),
                ('frequency', models.IntegerField(default=0)),
                ('albumArt', models.ImageField(blank=True, upload_to='images/')),
                ('lyrics', models.FileField(blank=True, upload_to='')),
                ('file', models.FileField(blank=True, storage=djongo.storage.GridFSStorage(collection='songs'), upload_to='songs/')),
                ('fingerprint', models.FileField(blank=True, storage=djongo.storage.GridFSStorage(collection='songs'), upload_to='fingerprints/')),
            ],
        ),
    ]
