# Generated by Django 2.2.20 on 2021-05-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='lyrics',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
