# Generated by Django 3.0.5 on 2021-04-06 20:20

from django.db import migrations, models
import djongo.models.fields
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('file', models.FileField(storage=djongo.storage.GridFSStorage(collection='songs'), upload_to='songs')),
                ('album', models.CharField(max_length=200)),
                ('yearReleased', models.IntegerField(max_length=4)),
            ],
        ),
    ]
