# Generated by Django 3.0.5 on 2021-04-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='file',
        ),
    ]
