# Generated by Django 3.0.5 on 2021-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='albumArt',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='songs',
            name='lyrics',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
