# Generated by Django 3.0.5 on 2021-04-21 20:09

from django.db import migrations, models
import django.utils.timezone
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_auto_20210417_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='songs',
            name='file',
            field=models.FileField(blank=True, storage=djongo.storage.GridFSStorage(collection='songs'), upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='songs',
            name='fingerprint',
            field=models.FileField(blank=True, storage=djongo.storage.GridFSStorage(collection='songs'), upload_to='fingerprints/'),
        ),
        migrations.AddField(
            model_name='songs',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='songs',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'spring'), ('Summer', 'summer'), ('Fall', 'fall'), ('Winter', 'winter')], max_length=10),
        ),
        migrations.AddField(
            model_name='songs',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songs',
            name='yearReleased',
            field=models.IntegerField(blank=True, max_length=4),
        ),
    ]
